import { Router } from 'express';
import matchingRoutes from './matchingRoutes.js';
import trainingRoutes from './trainingRoutes.js';
import scoringRoutes from './scoringRoutes.js';
import portfolioRoutes from './portfolioRoutes.js';
import advisorRoutes from './advisorRoutes.js';
import advisorIntelligenceRoutes from './advisorIntelligenceRoutes.js';
import ecosystemRoutes from './ecosystemRoutes.js';
import signalRoutes from './signalRoutes.js';
import auditRoutes from './auditRoutes.js';
import subscriptionRoutes from './subscriptionRoutes.js';
import platformSubscriptionRoutes from './platformSubscriptionRoutes.js';
import riskProfilingRoutes from './riskProfilingRoutes.js';
import authRoutes from './authRoutes.js';
import feedRoutes from './feedRoutes.js';
import adminRoutes from './adminRoutes.js';
import aiRoutes from './aiRoutes.js';
import kycRoutes from './kycRoutes.js';
import growthRoutes from './growthRoutes.js';
import paymentRoutes from './paymentRoutes.js';
import { authRateLimiter, transactionRateLimiter } from '../middleware/rateLimiter.js';

const router = Router();

router.use('/auth', authRateLimiter, authRoutes);
router.use('/matching', matchingRoutes);
router.use('/training', trainingRoutes);
router.use('/scoring', scoringRoutes);
router.use('/portfolio', portfolioRoutes);
router.use('/advisor', advisorRoutes);
router.use('/advisor-intelligence', advisorIntelligenceRoutes);
router.use('/ecosystem', ecosystemRoutes);
router.use('/audit', auditRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/platform-subscriptions', platformSubscriptionRoutes);
router.use('/risk-profiling', riskProfilingRoutes);
router.use('/feed', feedRoutes);
router.use('/signal', transactionRateLimiter, signalRoutes);
router.use('/admin', adminRoutes);
router.use('/ai', aiRoutes);
router.use('/kyc', transactionRateLimiter, kycRoutes);
router.use('/growth', growthRoutes);
router.use('/payments', transactionRateLimiter, paymentRoutes);

export default router;
