export const TRUST_SCORE_WEIGHTS = {
    CONSISTENCY: 0.4,
    RISK_MANAGEMENT: 0.3,
    CLIENT_FEEDBACK: 0.2,
    TRANSPARENCY: 0.1,
};

export const COMPATIBILITY_WEIGHTS = {
    RISK: 0.4,
    STRATEGY: 0.3,
    CAPITAL: 0.2,
    CONSISTENCY: 0.1,
};

export const RISK_ALIGNMENT_WEIGHTS = {
    ASSET_ALLOCATION: 0.5,
    VOLATILITY_FIT: 0.3,
    DIVERSIFICATION: 0.2,
};
